using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DEVES.IntegrationAPI.WebApi.DataAccessService.XrmEntity
{
    public class CustomerClientEntity
    {
        public string ContactId { get; set; }
        public object DefaultPriceLevelId { get; set; }
        public int CustomerSizeCode { get; set; }
        public int CustomerTypeCode { get; set; }
        public int PreferredContactMethodCode { get; set; }
        public int LeadSourceCode { get; set; }
        public object OriginatingLeadId { get; set; }
        public string OwningBusinessUnit { get; set; }
        public object PaymentTermsCode { get; set; }
        public int ShippingMethodCode { get; set; }
        public bool ParticipatesInWorkflow { get; set; }
        public bool IsBackofficeCustomer { get; set; }
        public string Salutation { get; set; }
        public object JobTitle { get; set; }
        public string FirstName { get; set; }
        public object Department { get; set; }
        public object NickName { get; set; }
        public object MiddleName { get; set; }
        public string LastName { get; set; }
        public object Suffix { get; set; }
        public object YomiFirstName { get; set; }
        public string FullName { get; set; }
        public object YomiMiddleName { get; set; }
        public object YomiLastName { get; set; }
        public object Anniversary { get; set; }
        public object BirthDate { get; set; }
        public object GovernmentId { get; set; }
        public string YomiFullName { get; set; }
        public string Description { get; set; }
        public object EmployeeId { get; set; }
        public int GenderCode { get; set; }
        public object AnnualIncome { get; set; }
        public int HasChildrenCode { get; set; }
        public int EducationCode { get; set; }
        public object WebSiteUrl { get; set; }
        public int FamilyStatusCode { get; set; }
        public object FtpSiteUrl { get; set; }
        public string EMailAddress1 { get; set; }
        public object SpousesName { get; set; }
        public object AssistantName { get; set; }
        public object EMailAddress2 { get; set; }
        public object AssistantPhone { get; set; }
        public object EMailAddress3 { get; set; }
        public bool DoNotPhone { get; set; }
        public object ManagerName { get; set; }
        public object ManagerPhone { get; set; }
        public bool DoNotFax { get; set; }
        public bool DoNotEMail { get; set; }
        public bool DoNotPostalMail { get; set; }
        public bool DoNotBulkEMail { get; set; }
        public bool DoNotBulkPostalMail { get; set; }
        public object AccountRoleCode { get; set; }
        public int TerritoryCode { get; set; }
        public bool IsPrivate { get; set; }
        public object CreditLimit { get; set; }
        public string CreatedOn { get; set; }
        public bool CreditOnHold { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public object NumberOfChildren { get; set; }
        public object ChildrensNames { get; set; }
        public string VersionNumber { get; set; }
        public string MobilePhone { get; set; }
        public object Pager { get; set; }
        public string Telephone1 { get; set; }
        public object Telephone2 { get; set; }
        public object Telephone3 { get; set; }
        public object Fax { get; set; }
        public object Aging30 { get; set; }
        public int StateCode { get; set; }
        public object Aging60 { get; set; }
        public int StatusCode { get; set; }
        public object Aging90 { get; set; }
        public object PreferredSystemUserId { get; set; }
        public object PreferredServiceId { get; set; }
        public object MasterId { get; set; }
        public object PreferredAppointmentDayCode { get; set; }
        public int PreferredAppointmentTimeCode { get; set; }
        public bool DoNotSendMM { get; set; }
        public bool Merged { get; set; }
        public object ExternalUserIdentifier { get; set; }
        public object SubscriptionId { get; set; }
        public object PreferredEquipmentId { get; set; }
        public object LastUsedInCampaign { get; set; }
        public string TransactionCurrencyId { get; set; }
        public object OverriddenCreatedOn { get; set; }
        public int ExchangeRate { get; set; }
        public object ImportSequenceNumber { get; set; }
        public int TimeZoneRuleVersionNumber { get; set; }
        public object UTCConversionTimeZoneCode { get; set; }
        public object AnnualIncome_Base { get; set; }
        public object CreditLimit_Base { get; set; }
        public object Aging60_Base { get; set; }
        public object Aging90_Base { get; set; }
        public object Aging30_Base { get; set; }
        public string OwnerId { get; set; }
        public object CreatedOnBehalfBy { get; set; }
        public bool IsAutoCreate { get; set; }
        public object ModifiedOnBehalfBy { get; set; }
        public object ParentCustomerId { get; set; }
        public object ParentCustomerIdType { get; set; }
        public object ParentCustomerIdName { get; set; }
        public int OwnerIdType { get; set; }
        public object ParentCustomerIdYomiName { get; set; }
        public object ProcessId { get; set; }
        public string EntityImageId { get; set; }
        public object StageId { get; set; }
        public object Business2 { get; set; }
        public object Company { get; set; }
        public object TraversedPath { get; set; }
        public object Home2 { get; set; }
        public object Callback { get; set; }
        public object CreatedByExternalParty { get; set; }
        public object ModifiedByExternalParty { get; set; }
        public object LastOnHoldTime { get; set; }
        public object SLAId { get; set; }
        public object OnHoldTime { get; set; }
        public object SLAInvokedId { get; set; }
        public object pfc_MobilePhone1 { get; set; }
        public object pfc_MobilePhone2 { get; set; }
        public string pfc_HomePhone { get; set; }
        public string pfc_crm_person_id { get; set; }
        public string pfc_polisy_client_id { get; set; }
        public object pfc_polisy_secuity_num { get; set; }
        public string pfc_citizen_id { get; set; }
        public string pfc_passport_id { get; set; }
        public bool pfc_customer_vip { get; set; }
        public string pfc_date_of_birth { get; set; }
        public string pfc_client_start_date { get; set; }
        public string pfc_client_date_time { get; set; }
        public object pfc_crm_key_code1 { get; set; }
        public object pfc_crm_key_code2 { get; set; }
        public string pfc_conv_date { get; set; }
        public int pfc_client_legal_status { get; set; }
        public int pfc_AMLO_flag { get; set; }
        public int pfc_language { get; set; }
        public int pfc_source_data { get; set; }
        public object pfc_date_of_death { get; set; }
        public int pfc_customer_sensitive_level { get; set; }
        public int pfc_customer_privilege_level { get; set; }
        public object pfc_cleansing_cusormer_profile_code { get; set; }
        public object pfc_alien_id { get; set; }
        public object pfc_driver_license { get; set; }
        public object pfc_polisy_nationality_code { get; set; }
        public object pfc_nationalityId { get; set; }
        public object pfc_title_personalId { get; set; }
        public object pfc_line_id { get; set; }
        public object pfc_facebook { get; set; }
        public object pfc_moblie_phone1 { get; set; }
        public object pfc_occupation { get; set; }
    }
}